-- Generated by Oracle SQL Developer Data Modeler 24.3.1.347.1153
--   at:        2026-01-09 22:13:35 GMT+01:00
--   site:      Oracle Database 21c
--   type:      Oracle Database 21c



-- predefined type, no DDL - MDSYS.SDO_GEOMETRY

-- predefined type, no DDL - XMLTYPE

CREATE TABLE cargo (
    cargoid               INTEGER NOT NULL,
    transport_transportid INTEGER NOT NULL,
    name                  VARCHAR2(200 CHAR),
    description           VARCHAR2(1000 CHAR),
    amount                INTEGER
);

ALTER TABLE cargo ADD CONSTRAINT cargo_pk PRIMARY KEY ( cargoid );

CREATE TABLE client (
    clientid INTEGER NOT NULL,
    name     VARCHAR2(200 CHAR),
    nip      INTEGER,
    address  VARCHAR2(1000 CHAR),
    phone    NUMBER
);

ALTER TABLE client ADD CONSTRAINT client_pk PRIMARY KEY ( clientid );

CREATE TABLE driver (
    driverid      INTEGER NOT NULL,
    name          VARCHAR2(300 CHAR),
    surname       VARCHAR2(300 CHAR),
    licensenumber INTEGER,
    phone         INTEGER,
    status        VARCHAR2(50 CHAR)
);

ALTER TABLE driver ADD CONSTRAINT driver_pk PRIMARY KEY ( driverid );

CREATE TABLE error (
    errorid     INTEGER NOT NULL,
    name        VARCHAR2(500 CHAR),
    description VARCHAR2(8000 CHAR),
    ticketdate  TIMESTAMP
);

ALTER TABLE error ADD CONSTRAINT error_pk PRIMARY KEY ( errorid );

CREATE TABLE invoice (
    invoiceid     INTEGER NOT NULL,
    job_jobid     INTEGER NOT NULL,
    "Number"      INTEGER,
    invoicenumber INTEGER,
    amount        INTEGER,
    issuedate     DATE,
    paymentdate   DATE,
    paymentstatus VARCHAR2(50 CHAR)
);

ALTER TABLE invoice ADD CONSTRAINT invoice_pk PRIMARY KEY ( invoiceid );

CREATE TABLE job (
    jobid           INTEGER NOT NULL,
    client_clientid INTEGER NOT NULL,
    startdate       DATE,
    status          VARCHAR2(50 CHAR),
    remarks         VARCHAR2(200 CHAR)
);

ALTER TABLE job ADD CONSTRAINT job_pk PRIMARY KEY ( jobid );

CREATE TABLE maintencelog (
    maintenanceid     INTEGER NOT NULL,
    vehicleid         INTEGER,
    servicetype       VARCHAR2(100 CHAR),
    odometerreading   INTEGER,
    description       VARCHAR2(1000 CHAR),
    cost              NUMBER,
    servicedate       DATE,
    nextservicedue    DATE,
    vehicle_vehicleid INTEGER NOT NULL
);

CREATE UNIQUE INDEX maintencelog__idx ON
    maintencelog (
        vehicle_vehicleid
    ASC );

ALTER TABLE maintencelog ADD CONSTRAINT user_pk PRIMARY KEY ( maintenanceid );

CREATE TABLE route (
    routeid               INTEGER NOT NULL,
    transport_transportid INTEGER NOT NULL,
    startpoint            VARCHAR2(1000 CHAR),
    endpoint              VARCHAR2(1000 CHAR),
    distance              NUMBER,
    estimatedtime         DATE
);

ALTER TABLE route ADD CONSTRAINT route_pk PRIMARY KEY ( routeid );

CREATE TABLE statushistory (
    statushistoryid INTEGER NOT NULL,
    job_jobid       INTEGER NOT NULL,
    userid          INTEGER,
    oldstatus       VARCHAR2(50 CHAR),
    newstatus       VARCHAR2(50 CHAR),
    changedate      TIMESTAMP
);

ALTER TABLE statushistory ADD CONSTRAINT statushistory_pk PRIMARY KEY ( statushistoryid );

CREATE TABLE transport (
    transportid       INTEGER NOT NULL,
    job_jobid         INTEGER NOT NULL,
    vehicle_vehicleid INTEGER NOT NULL,
    driver_driverid   INTEGER NOT NULL,
    startdate         DATE,
    enddate           DATE,
    cargomass         NUMBER,
    status            VARCHAR2(50 CHAR)
);

ALTER TABLE transport ADD CONSTRAINT transport_pk PRIMARY KEY ( transportid );

CREATE TABLE transportcost (
    transportcostid       INTEGER NOT NULL,
    transport_transportid INTEGER NOT NULL,
    description           VARCHAR2(100 CHAR),
    amount                NUMBER,
    currency              VARCHAR2(3 CHAR),
    dateincurred          TIMESTAMP,
    category              VARCHAR2(100 CHAR)
);

ALTER TABLE transportcost ADD CONSTRAINT transportcost_pk PRIMARY KEY ( transportcostid );

CREATE TABLE vehicle (
    vehicleid    INTEGER NOT NULL,
    licenseplate VARCHAR2(15 CHAR),
    type         VARCHAR2(50 CHAR),
    capacity     INTEGER,
    state        VARCHAR2(50 CHAR)
);

ALTER TABLE vehicle ADD CONSTRAINT vehicle_pk PRIMARY KEY ( vehicleid );

ALTER TABLE cargo
    ADD CONSTRAINT cargo_transport_fk FOREIGN KEY ( transport_transportid )
        REFERENCES transport ( transportid );

ALTER TABLE invoice
    ADD CONSTRAINT invoice_job_fk FOREIGN KEY ( job_jobid )
        REFERENCES job ( jobid );

ALTER TABLE job
    ADD CONSTRAINT job_client_fk FOREIGN KEY ( client_clientid )
        REFERENCES client ( clientid );

ALTER TABLE maintencelog
    ADD CONSTRAINT maintencelog_vehicle_fk FOREIGN KEY ( vehicle_vehicleid )
        REFERENCES vehicle ( vehicleid );

ALTER TABLE route
    ADD CONSTRAINT route_transport_fk FOREIGN KEY ( transport_transportid )
        REFERENCES transport ( transportid );

ALTER TABLE statushistory
    ADD CONSTRAINT statushistory_job_fk FOREIGN KEY ( job_jobid )
        REFERENCES job ( jobid );

ALTER TABLE transport
    ADD CONSTRAINT transport_driver_fk FOREIGN KEY ( driver_driverid )
        REFERENCES driver ( driverid );

ALTER TABLE transport
    ADD CONSTRAINT transport_job_fk FOREIGN KEY ( job_jobid )
        REFERENCES job ( jobid );

ALTER TABLE transport
    ADD CONSTRAINT transport_vehicle_fk FOREIGN KEY ( vehicle_vehicleid )
        REFERENCES vehicle ( vehicleid );

ALTER TABLE transportcost
    ADD CONSTRAINT transportcost_transport_fk FOREIGN KEY ( transport_transportid )
        REFERENCES transport ( transportid );



-- Oracle SQL Developer Data Modeler Summary Report: 
-- 
-- CREATE TABLE                            12
-- CREATE INDEX                             1
-- ALTER TABLE                             22
-- CREATE VIEW                              0
-- ALTER VIEW                               0
-- CREATE PACKAGE                           0
-- CREATE PACKAGE BODY                      0
-- CREATE PROCEDURE                         0
-- CREATE FUNCTION                          0
-- CREATE TRIGGER                           0
-- ALTER TRIGGER                            0
-- CREATE COLLECTION TYPE                   0
-- CREATE STRUCTURED TYPE                   0
-- CREATE STRUCTURED TYPE BODY              0
-- CREATE CLUSTER                           0
-- CREATE CONTEXT                           0
-- CREATE DATABASE                          0
-- CREATE DIMENSION                         0
-- CREATE DIRECTORY                         0
-- CREATE DISK GROUP                        0
-- CREATE ROLE                              0
-- CREATE ROLLBACK SEGMENT                  0
-- CREATE SEQUENCE                          0
-- CREATE MATERIALIZED VIEW                 0
-- CREATE MATERIALIZED VIEW LOG             0
-- CREATE SYNONYM                           0
-- CREATE TABLESPACE                        0
-- CREATE USER                              0
-- 
-- DROP TABLESPACE                          0
-- DROP DATABASE                            0
-- 
-- REDACTION POLICY                         0
-- 
-- ORDS DROP SCHEMA                         0
-- ORDS ENABLE SCHEMA                       0
-- ORDS ENABLE OBJECT                       0
-- 
-- ERRORS                                   0
-- WARNINGS                                 0
